// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSVXUQuTqpKMC0ZBImbDUpQt54CTzNqPM',
    appId: '1:619338813846:web:1f8f7b16e5fcff3774cdb7',
    messagingSenderId: '619338813846',
    projectId: 'test-70f90',
    authDomain: 'test-70f90.firebaseapp.com',
    databaseURL: 'https://test-70f90-default-rtdb.firebaseio.com',
    storageBucket: 'test-70f90.appspot.com',
    measurementId: 'G-0SDJF4CTZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gddTzRBU3h770jxMBmkQ-WwMY-b7RsM',
    appId: '1:619338813846:android:4977f44caaa001d674cdb7',
    messagingSenderId: '619338813846',
    projectId: 'test-70f90',
    databaseURL: 'https://test-70f90-default-rtdb.firebaseio.com',
    storageBucket: 'test-70f90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK9JDULQdknY27WIQxH8aNdsYAauXbLwA',
    appId: '1:619338813846:ios:8c8c550daba486ae74cdb7',
    messagingSenderId: '619338813846',
    projectId: 'test-70f90',
    databaseURL: 'https://test-70f90-default-rtdb.firebaseio.com',
    storageBucket: 'test-70f90.appspot.com',
    iosClientId: '619338813846-4rmeatitcvgphtrff2556hjkt9o3ks97.apps.googleusercontent.com',
    iosBundleId: 'com.example.new1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK9JDULQdknY27WIQxH8aNdsYAauXbLwA',
    appId: '1:619338813846:ios:8c8c550daba486ae74cdb7',
    messagingSenderId: '619338813846',
    projectId: 'test-70f90',
    databaseURL: 'https://test-70f90-default-rtdb.firebaseio.com',
    storageBucket: 'test-70f90.appspot.com',
    iosClientId: '619338813846-4rmeatitcvgphtrff2556hjkt9o3ks97.apps.googleusercontent.com',
    iosBundleId: 'com.example.new1',
  );
}
